apiVersion: clone.kubevirt.io/v1alpha1
kind: VirtualMachineClone
metadata:
  creationTimestamp: null
  name: web2-clone
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: golden-rhel
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: web2
  template: {}
status: {}
